name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: ["linter"]
    types:
      - completed
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/**'

permissions:
  contents: read

jobs:
  if: ${{ github.event.workflow_run.conclusion == 'success' }}
  linter:
    uses: ./.github/workflows/linter.yml

  build:
    runs-on: ubuntu-latest
    needs:
      - linter
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          check-latest: true
          go-version: 1.19
        id: go

      - name: Check out code into the Go module directory
      - uses: actions/checkout@v3

      - name: Cache go module
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Check and build
        run: |
            make check
            git diff --exit-code
            make build

      - name: Test
        run: |
          make test-full
          make test-race
          make test-pure
          make benchmark-pure

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
