name: Linter

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/**'

permissions:
  contents: read
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version: '1.19'
        id: go

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: --verbose
